{
 "title": "App",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Usuários logados",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "app_usuarios_logados_total", "legendFormat": "{{users}}" }
   ]
  },
  {
   "title": "Quantidade total de requisições",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by(instance) (rate(app_request_total[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Taxa de erro da API",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(sum(rate(app_request_total{statusCode='500'}[1m]))) / (sum(rate(app_request_total[1m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "requisições por segundo",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "rate(app_request_total[1m])", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Duração das requisições",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(app_request_duration_seconds_bucket[$__rate_interval])))",
     "legendFormat": "95%"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(app_request_duration_seconds_bucket[$__rate_interval])))",
     "legendFormat": "99%"
    },
    {
     "expr": "histogram_quantile(0.9, sum by(le) (rate(app_request_duration_seconds_bucket[$__rate_interval])))",
     "legendFormat": "90%"
    }
   ]
  }
 ]
}